### ISSUE TITLE
Problema al firmar un documento.

### ISSUE THREAD

**Issue by jorgeluisnt** [project-openubl/xml-builder#119]
Saludos.
Estoy usando las librerias y al firmar el documento el archivo generado contiene unos caracteres raros.

Intente cambiando la codificacion pero funciona 

![image](https://user-images.githubusercontent.com/8000472/76251748-9319d380-6215-11ea-8058-fee7be0b895f.png)

[myFile.txt](https://github.com/project-openubl/xml-builder/files/4308636/myFile.txt)

**Comment by carlosthe19916** [comment]
@jorgeluisnt podrías indicarme que método utilizas para descargar el archivo? Tal vez el error está siendo generado al momento de descargar el archivo.

- Puedes verificar esta URL http://xml-builder-signer-project-openubl.apps.us-west-1.starter.openshift-online.com/#/organizations/manage/master/documents e intentar generar un XML y descargarlo y veráz que no existen esos caracteres especiales que mencionas.
