### ISSUE TITLE
Problema al generar documento XML para resumen diario de boletas

### ISSUE THREAD

**Issue by krlzed2196** [project-openubl/xml-builder#125]
Estoy un poco confundido respecto a los campos solicitados en el SummaryDocumentInputModel, estoy tratando de enviar la petición mediante Postman y la respuesta es: 
{
    "error": "Exception executing consequence for rule \"Summary Document Detalle Item\" in org.openublpe.xmlbuilder.rules.files.sunat: java.util.NoSuchElementException: No value present",
    "errorDescription": null
}
Adjunto el archivo json enviado al servidor de OpenUBL, agradecería si pudieran ayudarme a identificar el error:
{
  "detalle": [
    {
      "cliente": {
        "nombre": "Carlos Arias Vera",
        "numeroDocumentoIdentidad": "71497913",
        "tipoDocumentoIdentidad": "1"
      },
      "icb": 0,
      "igv": 20,
      "importeTotal": 20,
      "serieNumero": "B005",
      "tipoComprobante": "03",
      "tipoOperacion": "01",
      "totalOperacionesExoneradas": 0,
      "totalOperacionesGratuitas": 0,
      "totalOperacionesGravadas": 0,
      "totalOperacionesInafectas": 0,
      "totalOtrosCargos": 0
    }
  ],
  "fechaEmision": 1584979150680,
  "fechaEmisionDocumentReference": 1584979150380,
  "firmante": {
    "razonSocial": "RAZON FIRMANTE",
    "ruc": "12345678911"
  },
  "moneda": "PEN",
  "numero": 144,
  "proveedor": {
    "codigoPostal": "0800",
    "nombreComercial": "INGRESE NOMBRE COMERCIAL",
    "razonSocial": "INGRESE RAZÓN SOCIAL",
    "ruc": "10203040506"
  }
}

**Comment by carlosthe19916** [comment]
@krlzed2196 hay dos problemas en el JSON que adjuntaste:
1. serieNumero: B005.- El campo `serieNumero` debe de contener la serie y número, por ejemplo: `serieNumero: B005-1`
2. "tipoOperacion": "01".- Este campo debe de tener un valor del CATALOGO 19, tu seleccionaste `01` pero debió ser `1` sin el Cero. Te dejo unos links aca:
- https://project-openubl.gitbook.io/xml-builder/guias_y_manuales
- http://www.sunat.gob.pe/legislacion/superin/2017/anexoVII-117-2017.pdf
- https://github.com/project-openubl/xml-builder/tree/master/core/src/main/java/org/openublpe/xmlbuilder/core/models/catalogs
- http://xml-builder-project-openubl.apps.us-west-1.starter.openshift-online.com/

Pero para resumir, "tipoOperacion" puede tener los siguientes valores:
- ADICIONAR
- MODIFICAR
- ANULADO
- 1
- 2
- 3 

Puedes escoger entre el valor numértico del catálogo o escoger el valor String del catálogo. Tu JSON quedaria como:

```
{
   "detalle":[
      {
         "cliente":{
            "nombre":"Carlos Arias Vera",
            "numeroDocumentoIdentidad":"71497913",
            "tipoDocumentoIdentidad":"1"
         },
         "icb":0,
         "igv":20,
         "importeTotal":20,
         "serieNumero":"B005-1",
         "tipoComprobante":"03",
         "tipoOperacion":"1",
         "totalOperacionesExoneradas":0,
         "totalOperacionesGratuitas":0,
         "totalOperacionesGravadas":0,
         "totalOperacionesInafectas":0,
         "totalOtrosCargos":0
      }
   ],
   "fechaEmision":1584979150680,
   "fechaEmisionDocumentReference":1584979150380,
   "firmante":{
      "razonSocial":"RAZON FIRMANTE",
      "ruc":"12345678911"
   },
   "moneda":"PEN",
   "numero":144,
   "proveedor":{
      "codigoPostal":"0800",
      "nombreComercial":"INGRESE NOMBRE COMERCIAL",
      "razonSocial":"INGRESE RAZÓN SOCIAL",
      "ruc":"10203040506"
   }
}
```
o usando catálogo String:
```
{
   "detalle":[
      {
         "cliente":{
            "nombre":"Carlos Arias Vera",
            "numeroDocumentoIdentidad":"71497913",
            "tipoDocumentoIdentidad":"DNI"
         },
         "icb":0,
         "igv":20,
         "importeTotal":20,
         "serieNumero":"B005-1",
         "tipoComprobante":"BOLETA",
         "tipoOperacion":"ADICIONAR",
         "totalOperacionesExoneradas":0,
         "totalOperacionesGratuitas":0,
         "totalOperacionesGravadas":0,
         "totalOperacionesInafectas":0,
         "totalOtrosCargos":0
      }
   ],
   "fechaEmision":1584979150680,
   "fechaEmisionDocumentReference":1584979150380,
   "firmante":{
      "razonSocial":"RAZON FIRMANTE",
      "ruc":"12345678911"
   },
   "moneda":"PEN",
   "numero":144,
   "proveedor":{
      "codigoPostal":"0800",
      "nombreComercial":"INGRESE NOMBRE COMERCIAL",
      "razonSocial":"INGRESE RAZÓN SOCIAL",
      "ruc":"10203040506"
   }
}
```
