### ISSUE TITLE
Duda sobre como generar comprobantes con percepción.

### ISSUE THREAD

**Issue by cmb1197** [project-openubl/xml-builder#139]
Quiero implementar facturación electrónica para un negocio pequeño. Estuve leyendo la documentación del xml-builder y no encontré como generar un comprobante con percepción. Según la guía de homologacion de SUNAT hay un caso de prueba llamado Operaciones con percepción. Mi duda era respecto a ese tipo de operación.

**Comment by carlosthe19916** [comment]
@cmb1197 como puedes ver acá https://project-openubl.github.io/xml-builder-docs/comprobantes/soportados/ las `Percepciones` todavía no están soportadas. Ya se tiene un avance sobre percepciones y retenciones por lo que la siguiente version incluirán esos documentos 
- https://github.com/project-openubl/xml-builder/blob/7819330d1807bcaad4a9fd2add23f27ceb0dc9c6/api/src/main/java/org/openublpe/xmlbuilder/api/resources/DocumentsResource.java#L253

Puedes empezar integrando tu software con los documentos soportados y para cuando termines con eso la nueva versión debería de haber sido lanzada.

**Comment by carlosthe19916** [comment]
@cmb1197 Cuando este [PR-141](https://github.com/project-openubl/xml-builder/pull/141) esté finalizado se tendrá la funcionalidad para percepciones y retenciones: https://github.com/project-openubl/xml-builder/pull/141

Te recuerdo que este es un projecto Open Source así que tu también puedes contribuir a mejorar el software. Has FORK al projecto y envía PRs cuando quieras contribuir. Saludos

**Comment by cmb1197** [comment]
Entiendo, gracias por contestar. Soy nuevo en esto de facturación electrónica y este proyecto es de gran ayuda.
