### ISSUE TITLE
Factura en una moneda extranjera??

### ISSUE THREAD

**Issue by ziggy72** [project-openubl/xml-builder#142]
Hola, he estado revisando la api y no veo alguna forma de enviar el codigo de la moneda en la factura.
es posible realizar esto?

**Comment by carlosthe19916** [comment]
@ziggy72 como puedes ver aca https://project-openubl.github.io/xml-builder-docs/configuracion/ puedes configurar la moneda. Eso responde a tu pregunta?

Me puedes explicar que es lo que quieres lograr? Si es necesario podemos abrir un nuevo ISSUE y crear la nueva funcionalidad si es necesario

**Comment by ziggy72** [comment]
Me refiero a que si es posible crear una factura con una moneda distinta a la configurada por defecto. Me pongo en el caso, por ejemplo, de una empresa que principalmente emita facturas en soles, pero en un mínimo porcentaje de casos, también lo haga en dolares. ¿Se tendría que volver a configurar la variable moneda? como se hace para modificar las variables de configuracion en windows? disculpa esto ultimo, no estoy muy familiarizado con java :(

**Comment by carlosthe19916** [comment]
Entiendo tu punto. La version 1.0.0.Final solo puede utilizar una moneda a la vez y esta es configurada al arrancar el servidor. 
1. Si lo que deseas es soportar varias monedas es necesario crear esta funcionalidad, la siguiente versión deberá tener eso. Estoy haciendo una lista de peticiones y después trabajaré en ello.
2. Como puedes ver en https://project-openubl.github.io/xml-builder-docs/configuracion/ puedes configurar el servidor en todo tipo de sistemas operativos y tambien en contenedores.  Si lo que quieres es levantar en java puedes ejecutar `java -Dopenubl.defaultMoneda=USD -jar xml-builder-api-*-runner.jar`. Para producción, sin embargo, te recomiendo usar contenedores como lo está descrito en el mismo manual

**Comment by ziggy72** [comment]
@carlosthe19916 gracias por tu respuesta
