### ISSUE TITLE
Por alguna razon cuando lo instale en ubuntu 18.04 via docker, se me daño a la media hora de esta funcionando.

### ISSUE THREAD

**Issue by Fredyg1965** [project-openubl/xml-builder#149]
Instale la ultima versión de xml-builder en un vps en digitalocean, lo cual se hizo perfectamente, cuando cree una organización, subi un certificado digital y quise probar con postman, cayo el docker que tiene el xml-builder y ya no se pudo levantar, tuve que reinstalar de nuevo todo.

**Comment by carlosthe19916** [comment]
@Fredyg1965 ¿podrias incluir el log de xml-builder? xml-builder siempre tiene un log, esto nos podría ayudar a saber cual fue el error.
