### ISSUE TITLE
UI: Interfaz para crear comprobantes electrónicos

### ISSUE THREAD

**Issue by carlosthe19916** [project-openubl/xml-builder#55]
**Is your feature request related to a problem? Please describe.**
Necesitamos una forma en el usuario vea Vizualmente la forma de crear un comprobante electrónico.

**Describe the solution you'd like**
Crear una interfaz UI donde se pueda crear uno o más comprobantes electrónicos.

**Comment by solopromiguel** [comment]
Hola , este proyecto es ya una Api Rest? seria una gran ventaja poder integrarlo con cualquier cliente .

**Comment by carlosthe19916** [comment]
> Hola , este proyecto es ya una Api Rest? seria una gran ventaja poder integrarlo con cualquier cliente .

@solopromiguel Absolutamente todo el proyecto está basado en REST APIs, las interfaces son solamente son un plus. Puedes ver que en la pagina principal del proyecto hay un ejemplo de cómo crear un comprobante usando el REST API https://github.com/project-openubl/xml-builder#crear-factura-electr%C3%B3nica-1

Puedes ver un poco de la idea de los APIs del proyecto en https://github.com/project-openubl/xml-builder#crear-factura-electr%C3%B3nica-1

Estos son los links de las APIs:
- https://app.swaggerhub.com/apis-docs/project-openubl/xml-builder/1.3
- https://app.swaggerhub.com/apis-docs/project-openubl/xml-builder-signer

**Comment by carlosthe19916** [comment]
PR para resolver este issue: https://github.com/project-openubl/xml-builder/pull/57. El PR esta todavia en progreso

**Comment by carlosthe19916** [comment]
https://github.com/project-openubl/xml-builder/pull/57 has been merged
